name: Monthly contributor report

on:
  workflow_dispatch:
  schedule:
    - cron: "3 2 1 * *"  # Runs at 02:03 UTC on the 1st of every month

permissions:
  contents: read
  issues: write

jobs:
  contributor_report:
    name: contributor report
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPOSITORY: glowing-jellyfishing/glowing-jellyfishing.github.io
      SPONSOR_INFO: true

    steps:
      - name: Get dates for last month
        shell: bash
        run: |
          start_date=$(date -d "last month" +%Y-%m-01)
          end_date=$(date -d "$start_date +1 month -1 day" +%Y-%m-%d)
          echo "START_DATE=$start_date" >> "$GITHUB_ENV"
          echo "END_DATE=$end_date" >> "$GITHUB_ENV"

      - name: Run contributor action
        uses: github/contributors@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          START_DATE: ${{ env.START_DATE }}
          END_DATE: ${{ env.END_DATE }}
          REPOSITORY: glowing-jellyfishing/glowing-jellyfishing.github.io
          SPONSOR_INFO: true

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Monthly contributor report
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./contributors.md
          assignees: glowing-jellyfishing
